# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaSistema.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janelaPrincipal(object):
    def setupUi(self, janelaPrincipal):
        janelaPrincipal.setObjectName("janelaPrincipal")
        janelaPrincipal.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janelaPrincipal.sizePolicy().hasHeightForWidth())
        janelaPrincipal.setSizePolicy(sizePolicy)
        janelaPrincipal.setMinimumSize(QtCore.QSize(800, 600))
        janelaPrincipal.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(janelaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.caixa = QtWidgets.QLabel(self.centralwidget)
        self.caixa.setGeometry(QtCore.QRect(320, 10, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.caixa.setFont(font)
        self.caixa.setStyleSheet("color: red\n"
"")
        self.caixa.setObjectName("caixa")
        self.opcao = QtWidgets.QLabel(self.centralwidget)
        self.opcao.setGeometry(QtCore.QRect(20, 90, 751, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.opcao.setFont(font)
        self.opcao.setStyleSheet("color: red;\n"
"")
        self.opcao.setText("")
        self.opcao.setObjectName("opcao")
        self.msg = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.msg.setEnabled(False)
        self.msg.setGeometry(QtCore.QRect(10, 230, 771, 291))
        self.msg.setStyleSheet("font: 75 28pt \"MS Shell Dlg 2\";\n"
"border-radius:10px;\n"
"border: 1px solid red;")
        self.msg.setPlainText("")
        self.msg.setObjectName("msg")
        self.fechar = QtWidgets.QPushButton(self.centralwidget)
        self.fechar.setGeometry(QtCore.QRect(280, 530, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.fechar.setFont(font)
        self.fechar.setStyleSheet("border-radius:10px;\n"
"background-color: red;\n"
"color:blue;")
        self.fechar.setObjectName("fechar")
        janelaPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(janelaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(janelaPrincipal)

    def retranslateUi(self, janelaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        janelaPrincipal.setWindowTitle(_translate("janelaPrincipal", "FRINEPE ALERTA SERVIDOR"))
        self.label.setText(_translate("janelaPrincipal", "CAIXA "))
        self.caixa.setText(_translate("janelaPrincipal", "0"))
        self.fechar.setText(_translate("janelaPrincipal", "FECHAR"))
